# Generated by Django 4.2 on 2023-04-19 11:06

import django.contrib.auth.password_validation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0004_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(help_text='Max symbols is 16', max_length=128, validators=[django.contrib.auth.password_validation.validate_password]),
        ),
    ]
